name: cfn-github-actions
on:
  pull_request:
    branches:
    - main
jobs:
  check-cfn:
    runs-on: ubuntu-latest
    steps:
      - uses: stelligent/cfn_nag@v0.8.6
        with:
          input_path: .
          extra_args: --fail-on-warnings -o json

