name: learn-github-actions
on:
  pull_request:
    branches:
    - main
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: stelligent/cfn_nag@v0.8.6
      - uses: ryof/cloudformation-lint-action@1.0.1
